const Map<String, String> gasBrands = {
  'NEPAL_GAS': 'Nepal Gas',
  'STC': 'STC Gas',
  'EVEREST': 'Everest Gas',
  'SIDDHARTHA': 'Siddhartha Gas',
  'KOSHI': 'Koshi Gas',
  'BHERI': 'Bheri Gas',
  'GANDAKI': 'Gandaki Gas',
  'JANAKI': 'Janaki Gas',
  'TRISHULI': 'Trishuli Gas',
  'BUTWAL': 'Butwal Gas',
  'SAGAR': 'Sagar Gas',
  'SURYA': 'Surya Gas',
  'BABA': 'Baba Gas',
  'OM': 'OM Gas',
  'NARAYANI': 'Narayani Gas',
  'MANOJ': 'Manoj Gas',
  'GRIHALAXMI': 'Grihalaxmi Gas',
  'PATHIBHARA': 'Pathibhara Gas',
  'MECHI': 'Mechi Gas',
  'LUMBINI': 'Lumbini Gas',
  'HIMAL': 'Himal Gas',
  'JUALA': 'Jwala Gas',
  'KANKAI': 'Kankai Gas',
  'ROYAL': 'Royal Gas',
  'SHREERAM': 'Shreeram Gas',
};
