# Generated by Django 6.0.3 on 2026-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dealer_closing_time_dealer_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysighting',
            name='brand',
            field=models.CharField(blank=True, choices=[('NEPAL_GAS', 'Nepal Gas'), ('STC', 'STC Gas'), ('EVEREST', 'Everest Gas'), ('SIDDHARTHA', 'Siddhartha Gas'), ('KOSHI', 'Koshi Gas'), ('BHERI', 'Bheri Gas'), ('GANDAKI', 'Gandaki Gas'), ('JANAKI', 'Janaki Gas'), ('TRISHULI', 'Trishuli Gas'), ('BUTWAL', 'Butwal Gas'), ('SAGAR', 'Sagar Gas'), ('SURYA', 'Surya Gas'), ('BABA', 'Baba Gas'), ('OM', 'OM Gas'), ('NARAYANI', 'Narayani Gas'), ('MANOJ', 'Manoj Gas'), ('GRIHALAXMI', 'Grihalaxmi Gas'), ('PATHIBHARA', 'Pathibhara Gas'), ('MECHI', 'Mechi Gas'), ('LUMBINI', 'Lumbini Gas'), ('HIMAL', 'Himal Gas'), ('JUALA', 'Jwala Gas'), ('KANKAI', 'Kankai Gas'), ('ROYAL', 'Royal Gas'), ('SHREERAM', 'Shreeram Gas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='brand',
            field=models.CharField(choices=[('NEPAL_GAS', 'Nepal Gas'), ('STC', 'STC Gas'), ('EVEREST', 'Everest Gas'), ('SIDDHARTHA', 'Siddhartha Gas'), ('KOSHI', 'Koshi Gas'), ('BHERI', 'Bheri Gas'), ('GANDAKI', 'Gandaki Gas'), ('JANAKI', 'Janaki Gas'), ('TRISHULI', 'Trishuli Gas'), ('BUTWAL', 'Butwal Gas'), ('SAGAR', 'Sagar Gas'), ('SURYA', 'Surya Gas'), ('BABA', 'Baba Gas'), ('OM', 'OM Gas'), ('NARAYANI', 'Narayani Gas'), ('MANOJ', 'Manoj Gas'), ('GRIHALAXMI', 'Grihalaxmi Gas'), ('PATHIBHARA', 'Pathibhara Gas'), ('MECHI', 'Mechi Gas'), ('LUMBINI', 'Lumbini Gas'), ('HIMAL', 'Himal Gas'), ('JUALA', 'Jwala Gas'), ('KANKAI', 'Kankai Gas'), ('ROYAL', 'Royal Gas'), ('SHREERAM', 'Shreeram Gas')], default='NEPAL_GAS', max_length=50),
        ),
    ]
