name: Sync to Hugging Face Space

# on:
#   push:
#     branches: [main]
on:
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Create a clean deployment folder to avoid pushing mobile binaries to HF
          mkdir hf_deploy
          cp -r backend hf_deploy/
          cp Dockerfile hf_deploy/
          cp README.md hf_deploy/
          
          cd hf_deploy
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy backend to HF Space"
          git push --force https://x-access-token:$HF_TOKEN@huggingface.co/spaces/Bishal26/gas_cylinder_management.git HEAD:main
